#           SPATIAL PREPROCESSING

### Importing the necessary libraries

In [39]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [40]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

### Load the dataset

In [41]:
df=pd.read_csv("/workspaces/Spatio-Temporal-EV-Adoption-Forecasting-Project/notebook/data/EV_Population_2.csv")

In [42]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJYGDEE1L,King,Seattle,WA,98122.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291,0,37.0,125701579,POINT (-122.30839 47.610365),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
1,7SAYGDEE9P,Snohomish,Bothell,WA,98021.0,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,1.0,244285107,POINT (-122.179458 47.802589),PUGET SOUND ENERGY INC,5.306105e+10
2,5YJSA1E4XK,King,Seattle,WA,98109.0,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,36.0,156773144,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5YJSA1E27G,King,Issaquah,WA,98027.0,2016,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,5.0,165103011,POINT (-122.03646 47.534065),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,5YJYGDEE5M,Kitsap,Suquamish,WA,98392.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,23.0,205138552,POINT (-122.55717 47.733415),PUGET SOUND ENERGY INC,5.303594e+10

In [43]:
df.shape

(177866, 17)

### Converting the column name into lower case for ease

In [44]:
# Standardize column names
df.columns = df.columns.str.lower().str.replace(' ', '_')

# Check the column names
df.columns

Index(['vin_(1-10)', 'county', 'city', 'state', 'postal_code', 'model_year',
       'make', 'model', 'electric_vehicle_type',
       'clean_alternative_fuel_vehicle_(cafv)_eligibility', 'electric_range',
       'base_msrp', 'legislative_district', 'dol_vehicle_id',
       'vehicle_location', 'electric_utility', '2020_census_tract'],
      dtype='object')

### Replaced few names

In [45]:
df.columns=df.columns.str.replace('county','country')
df.columns=df.columns.str.replace('clean_alternative_fuel_vehicle_(cafv)_eligibility','cafv_eligibility')

### Dropped unnecessary column

In [46]:
df.drop('vin_(1-10)',axis=1, inplace=True)

In [47]:
df.columns

Index(['country', 'city', 'state', 'postal_code', 'model_year', 'make',
       'model', 'electric_vehicle_type', 'cafv_eligibility', 'electric_range',
       'base_msrp', 'legislative_district', 'dol_vehicle_id',
       'vehicle_location', 'electric_utility', '2020_census_tract'],
      dtype='object')

### Checking NaN values

In [48]:

df.isnull().sum()

country                    5
city                       5
state                      0
postal_code                5
model_year                 0
make                       0
model                      0
electric_vehicle_type      0
cafv_eligibility           0
electric_range             0
base_msrp                  0
legislative_district     389
dol_vehicle_id             0
vehicle_location           9
electric_utility           5
2020_census_tract          5
dtype: int64

In [49]:

df.dtypes

country                   object
city                      object
state                     object
postal_code              float64
model_year                 int64
make                      object
model                     object
electric_vehicle_type     object
cafv_eligibility          object
electric_range             int64
base_msrp                  int64
legislative_district     float64
dol_vehicle_id             int64
vehicle_location          object
electric_utility          object
2020_census_tract        float64
dtype: object

Converting numeric data into Int64 datatype

In [50]:
df['postal_code']=pd.to_numeric(df['postal_code'],errors='coerce').astype('Int64')
df['model_year']=pd.to_numeric(df['model_year'],errors='coerce').astype('Int64')
df['electric_range']=pd.to_numeric(df['electric_range'],errors='coerce').astype('Int64')
df['base_msrp']=pd.to_numeric(df['base_msrp'],errors='coerce').astype('Int64')
df['legislative_district']=pd.to_numeric(df['legislative_district'],errors='coerce').astype('Int64')
df['dol_vehicle_id']=pd.to_numeric(df['dol_vehicle_id'],errors='coerce').astype('Int64')
df['2020_census_tract']=pd.to_numeric(df['2020_census_tract'],errors='coerce').astype('Int64')

In [51]:
df.isnull().sum()

country                    5
city                       5
state                      0
postal_code                5
model_year                 0
make                       0
model                      0
electric_vehicle_type      0
cafv_eligibility           0
electric_range             0
base_msrp                  0
legislative_district     389
dol_vehicle_id             0
vehicle_location           9
electric_utility           5
2020_census_tract          5
dtype: int64

Filling NaN values whose dtype is integer with their respective median

In [52]:
df['postal_code']= df['postal_code'].fillna(df['postal_code'].median())

In [53]:
df['legislative_district']= df['legislative_district'].fillna(df['legislative_district'].median())

In [54]:
df['2020_census_tract']= df['2020_census_tract'].fillna(df['2020_census_tract'].median())

In [55]:
df.isnull().sum()

country                  5
city                     5
state                    0
postal_code              0
model_year               0
make                     0
model                    0
electric_vehicle_type    0
cafv_eligibility         0
electric_range           0
base_msrp                0
legislative_district     0
dol_vehicle_id           0
vehicle_location         9
electric_utility         5
2020_census_tract        0
dtype: int64

Filling NaN of categorical columns with "Unknown" term

In [56]:
df.fillna('Unknown', inplace=True)

In [57]:
df.isnull().sum()

country                  0
city                     0
state                    0
postal_code              0
model_year               0
make                     0
model                    0
electric_vehicle_type    0
cafv_eligibility         0
electric_range           0
base_msrp                0
legislative_district     0
dol_vehicle_id           0
vehicle_location         0
electric_utility         0
2020_census_tract        0
dtype: int64

In [58]:
df.head()

,country,city,state,postal_code,model_year,make,model,electric_vehicle_type,cafv_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,electric_utility,2020_census_tract
0,King,Seattle,WA,98122,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291,0,37,125701579,POINT (-122.30839 47.610365),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033007800
1,Snohomish,Bothell,WA,98021,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,1,244285107,POINT (-122.179458 47.802589),PUGET SOUND ENERGY INC,53061051938
2,King,Seattle,WA,98109,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,36,156773144,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033006800
3,King,Issaquah,WA,98027,2016,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,5,165103011,POINT (-122.03646 47.534065),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033032104
4,Kitsap,Suquamish,WA,98392,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,23,205138552,POINT (-122.55717 47.733415),PUGET SOUND ENERGY INC,53035940100

In [59]:
df.dtypes

country                  object
city                     object
state                    object
postal_code               Int64
model_year                Int64
make                     object
model                    object
electric_vehicle_type    object
cafv_eligibility         object
electric_range            Int64
base_msrp                 Int64
legislative_district      Int64
dol_vehicle_id            Int64
vehicle_location         object
electric_utility         object
2020_census_tract         Int64
dtype: object

As we can see there's huge amount of data which we can't easily count

Applying Label encoder

In [60]:
label_encoder = LabelEncoder()
df['cafv_eligibility'] = label_encoder.fit_transform(df['cafv_eligibility'])
df['electric_utility'] = label_encoder.fit_transform(df['electric_utility'])
df['2020_census_tract'] = label_encoder.fit_transform(df['2020_census_tract'])

In [61]:
label_encoder

LabelEncoder()

In [62]:
print(df[['cafv_eligibility','electric_utility','2020_census_tract']])

        cafv_eligibility  electric_utility  2020_census_tract
0                      0                57                820
1                      1                73               1692
2                      0                57                799
3                      0                74               1153
4                      1                73               1259
...                  ...               ...                ...
177861                 1                74               1405
177862                 1                22               1318
177863                 1                72                637
177864                 1                74               1125
177865                 1                19               1537

[177866 rows x 3 columns]

Applying One-hot encoding

In [63]:
df=pd.get_dummies(df,columns=['country','state','electric_vehicle_type'] , drop_first=True, dtype='Int64')

In [64]:
df.shape

(177866, 255)

Applying Frequency-Encoding

In [65]:
freq_map = df['city'].value_counts(normalize=True) 
df['city'] = df['city'].map(df['city'].value_counts())

In [66]:
freq_map = df['make'].value_counts(normalize=True)  
df['make'] = df['make'].map(df['make'].value_counts())

In [67]:
import pandas as pd
from sklearn.feature_extraction import FeatureHasher

# Initialize FeatureHasher
hasher = FeatureHasher(n_features=8, input_type='string')

# Transform the 'model' column (convert each value to a list)
hashed_features = hasher.transform([[m] for m in df['model'].astype(str)])

# Convert to a DataFrame
hashed_df = pd.DataFrame(hashed_features.toarray(), columns=[f'hash_{i}' for i in range(8)])

# Combine with original DataFrame
df = pd.concat([df.drop(columns=['model']), hashed_df], axis=1)

In [68]:
df.head()

,city,postal_code,model_year,make,cafv_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,...,state_WY,electric_vehicle_type_Plug-in Hybrid Electric Vehicle (PHEV),hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7
0,29447,98122,2020,79659,0,291,0,37,125701579,POINT (-122.30839 47.610365),...,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,5863,98021,2023,79659,1,0,0,1,244285107,POINT (-122.179458 47.802589),...,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,29447,98109,2019,79659,0,270,0,36,156773144,POINT (-122.34848 47.632405),...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,2764,98027,2016,79659,0,210,0,5,165103011,POINT (-122.03646 47.534065),...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,69,98392,2021,79659,1,0,0,23,205138552,POINT (-122.55717 47.733415),...,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [69]:
df.dtypes

city                  int64
postal_code           Int64
model_year            Int64
make                  int64
cafv_eligibility      int64
                     ...
hash_3              float64
hash_4              float64
hash_5              float64
hash_6              float64
hash_7              float64
Length: 262, dtype: object

In [70]:
df.shape

(177866, 262)

In [71]:
df.isnull().sum().sum()

np.int64(0)

Extracting "Latitude" & "Longitude" from Vehicle Location column

In [72]:
import re
import pandas as pd

def extract_lat_lon(wkt_str):
    if pd.isna(wkt_str):
        return None, None
    match = re.search(r'POINT\s*\(([-\d\.]+)\s+([-\d\.]+)\)', wkt_str)
    if match:
        lon, lat = match.groups()
        return float(lat), float(lon)
    return None, None

df[['latitude', 'longitude']] = df['vehicle_location'].apply(
    lambda x: pd.Series(extract_lat_lon(x))
)

In [73]:
print(df[['latitude', 'longitude']].head())

    latitude   longitude
0  47.610365 -122.308390
1  47.802589 -122.179458
2  47.632405 -122.348480
3  47.534065 -122.036460
4  47.733415 -122.557170

In [74]:
df.head(3)

,city,postal_code,model_year,make,cafv_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,...,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,latitude,longitude
0,29447,98122,2020,79659,0,291,0,37,125701579,POINT (-122.30839 47.610365),...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,47.610365,-122.308390
1,5863,98021,2023,79659,1,0,0,1,244285107,POINT (-122.179458 47.802589),...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,47.802589,-122.179458
2,29447,98109,2019,79659,0,270,0,36,156773144,POINT (-122.34848 47.632405),...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,47.632405,-122.348480

In [75]:
obj_column_names = df.select_dtypes(include=['object']).columns
print(obj_column_names)

Index(['vehicle_location'], dtype='object')

As we extracted the Latitudes and Longitudes so we can easily drop Vehicle Location column

In [76]:
df.drop(columns=['vehicle_location'], inplace=True)

In [77]:
scaler = StandardScaler()
numerical_features = ['postal_code','model_year','electric_range','base_msrp','legislative_district','dol_vehicle_id']

df[numerical_features] = scaler.fit_transform(df[numerical_features])

In [78]:
df.head(10)

,city,postal_code,model_year,make,cafv_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,electric_utility,...,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,latitude,longitude
0,29447,-0.020657,-0.172448,79659,0,2.523975,-0.128384,0.528607,-1.246277,57,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,47.610365,-122.308390
1,5863,-0.062009,0.831106,79659,1,-0.639721,-0.128384,-1.891247,0.317125,73,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,47.802589,-122.179458
2,29447,-0.025979,-0.506966,79659,0,2.295667,-0.128384,0.461389,-0.836630,57,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,47.632405,-122.348480
3,2764,-0.059553,-1.510520,79659,0,1.643359,-0.128384,-1.622374,-0.726810,74,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,47.534065,-122.036460
4,69,0.089890,0.162070,79659,1,-0.639721,-0.128384,-0.412447,-0.198982,73,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,47.733415,-122.557170
5,265,0.173823,-1.176002,9199,2,-0.411413,-0.128384,-1.824029,-1.294317,73,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.941260,-122.610230
6,658,0.299110,-2.514074,13998,0,0.175665,-0.128384,-1.017411,-0.924255,65,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,46.553505,-120.477805
7,5863,-0.065694,-0.841484,7432,2,-0.324438,-0.128384,-1.891247,0.927814,73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,47.820245,-122.187300
8,1069,0.079245,-1.845038,13998,0,0.273511,-0.128384,-0.210793,-1.093072,73,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,47.537300,-122.639265
9,1897,-0.070198,0.496588,7570,0,-0.313566,-0.128384,1.200788,0.263614,74,...,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,47.338406,-122.284939

In [79]:
import os
output_path = '/workspaces/Spatio-Temporal-EV-Adoption-Forecasting-Project/data/processed/ev_spatial.csv'
compressed_output = os.path.join(os.path.dirname(output_path), "ev_spatial_preprocessed.csv.gz")
df.to_csv(compressed_output, index=False, compression="gzip")